repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: detect-private-key 
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/PyCQA/bandit/blob/main/.pre-commit-hooks.yaml
  rev: v1.7.4
  hooks:
  - id: bandit

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell 

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.278
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
    