name: bandit

on: 
  workflow_call:

jobs:

  security:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3  
          
    - name: Bandit security check
      uses: jpetrucciani/bandit-check@main
      with:
        path: '.'
        bandit_flags: '-c pyproject.toml -r'