name: bandit

on: 
  workflow_call:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Bandit security check
      uses: jpetrucciani/bandit-check@main
      with:
        path: '.'
        bandit_flags: '-c pyproject.toml -r'