name: docs

on: 
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build documentation with MkDocs
        run: mkdocs build

      - name: Deploy documentation to GitHub Pages
        run: mkdocs gh-deploy --force --clean --verbose