name: docs

on: 
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install mkdocs
        run: pip install mkdocs

      - name: Build docs
        run: mkdocs build

      - name: Deploy docs
        run: mkdocs gh-deploy --force --clean --verbose