name: test

on: 
  workflow_call:

# defaults:
#   run:
#     shell: bash

# env:
#   LANG: en_US.utf-8
#   LC_ALL: en_US.utf-8
#   PYTHONIOENCODING: UTF-8

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            python-version: ['3.10', '3.11']
            os: [ubuntu-latest, macOS-latest, windows-latest]
    
        steps:
          - name: Checkout
            uses: actions/checkout@v3
      
          - name: Set up PDM
            uses: pdm-project/setup-pdm@v2
            with:
              python-version: ${{ matrix.python-version }}
      
          - name: Resolving dependencies
            run: pdm lock -v --no-cross-platform
            
          - name: Install dependencies
            run: pdm install

          - name: Run tests with pytest
            run: |
              pdm run -v pytest tests

    