name: pytest

on: 
  workflow_call:

jobs:

  testing:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup PDM
      uses: ./
      id: setup-pdm
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
        allow-python-prereleases: true

    - name: Check output
      run: |
        echo ${{ steps.setup-pdm.outputs.pdm-bin }}
        echo ${{ steps.setup-pdm.outputs.pdm-version }}
        echo ${{ steps.setup-pdm.outputs.python-path }}
        echo ${{ steps.setup-pdm.outputs.python-version }}

    - name: Install dependencies
      run: pdm install -v && pdm info

    - name: Verify python version
      run: pdm run python test.py
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}

