# Unlike most model workflows and templates, which put all of the relevant 
# GitHub Actions in one or two files, this template takes a different approach,
# consistent with the typical "separation of concerns" principles of modern
# coding. This workflow uses the "call-workflow" instruction and the 
# on: "workflow_call" trigger to make it easier to change or create alternate
# workflows.

name: release

on:
  push:
    branches:
      - 'development/*'

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8
      
jobs:
  main:
    name: Merge development to to main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"
          pr_reviewer: "jessesquires"
          pr_assignee: "jessesquires"

      - name: Enable automerge
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge

