# GitHub Action for ruff formatter

name: ruff

on: 
  workflow_call:

jobs:

  format:

    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Ruff
      uses: chartboost/ruff-action@v1
      with:
        src: "./src"

      # - name: Install Ruff dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install ruff

      # Include `--format=github` to enable automatic inline annotations.

    - name: Run Ruff
      run: ruff check --format=github .