name: ruff

on: 
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install ruff
        uses: chartboost/ruff-action@v1
      - name: Install ruff dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Include `--format=github` to enable automatic inline annotations.
      - name: Run ruff
        run: ruff check --format=github .