name: update

on: 
  workflow_call:

env:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
    PYTHONIOENCODING: UTF-8
  
jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PDM
      uses: ./
      id: setup-pdm
      with:
        python-version: ${{ matrix.python-version }}
        cache: true
        allow-python-prereleases: true

    - name: Check output
      run: |
        echo ${{ steps.setup-pdm.outputs.pdm-bin }}
        echo ${{ steps.setup-pdm.outputs.pdm-version }}
        echo ${{ steps.setup-pdm.outputs.python-path }}
        echo ${{ steps.setup-pdm.outputs.python-version }}

    - name: Install dependencies
      run: pdm install -v && pdm info

    - name: Verify python version
      run: pdm run python test.py
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}

  security:

    runs-on: ubuntu-latest

    steps: 
      
    - name: Checkout
      uses: actions/checkout@v3

    - uses: jpetrucciani/bandit-check@master
      with:
        path: '.'
        bandit_flags: '-c pyproject.toml -r'
  
  format:

    runs-on: ubuntu-latest
    
    steps:
      
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Ruff
      uses: chartboost/ruff-action@v1
      with:
        src: "./src"

    - name: Run Ruff
      run: ruff check --format=github .

  docs:

    runs-on: ubuntu-latest
    
    steps:
      
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build documentation with MkDocs
      run: pdm run mkdocs build

    - name: Deploy documentation to GitHub Pages
      run: pdm run mkdocs gh-deploy --force --clean --verbose

