# Unlike most model workflows and templates, which put all of the relevant 
# GitHub Actions in one or two files, this template takes a different approach,
# consistent with the typical "separation of concerns" principles of modern
# coding. This workflow uses the "call-workflow" instruction and the 
# on: "workflow_call" trigger to make it easier to change or create alternate
# workflows.

name: update

on: push

env:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
    PYTHONIOENCODING: UTF-8
  
jobs:

  call-test:
    uses: ./.github/workflows/pytest.yml

  call-security:
    needs: call-test
    uses: ./.github/workflows/bandit.yml
  
  call-format:
    needs: call-security
    uses: ./.github/workflows/ruff.yml

  call-docs:
    needs: call-format
    uses: ./.github/workflows/docs.yml

